# Generated by Django 6.1 on 2026-08-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('cinemahall', 'show_time', 'movie')},
        ),
    ]
