# Generated by Django 6.0.8 on 2026-09-11 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_masterreservation_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
